### ISSUE TITLE
🚨 Login 로직 관련 디테일 수정

### ISSUE THREAD

**Issue by khyaejin** [HSU-Web-Framework1-Artory/Artory#77]
## 💡 About
로그인 로직 관련 디테일 수정

## 📝 To Do
- [x] 헤더 Login -> Logout(or blank) 로 변경되도록 수정
- [x] socialLogin 후 스플래시 화면 만들어둔 컴포넌트로 실행되도록 수정

## ✅ Issue check list
- [x]  Assignees, Labels 확인하기
