### ISSUE TITLE
🚨 Mypage 페이지 - 데이터 처리 로직 수정

### ISSUE THREAD

**Issue by khyaejin** [HSU-Web-Framework1-Artory/Artory#78]
## 💡 About
무엇에 관한 이슈인지 소개해주세요.

## 📝 To Do
- [x] josn 더미데이터 사용하도록 수정
- [x] 로컬 스토리지에서 닉네임, 프로필 가져오기
- [x] home 푸터 수정
- [x] mystory 저장한 스토리 로직 수정

## ✅ Issue check list
- [x] Assignees, Labels 확인하기
